import{a as v,i as c}from"./assets/vendor-CBLHhzjb.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const L="49725006-00816a3e1de0585a9b0ca4d46",b="https://pixabay.com/api/";async function y(o,t){return(await v.get(b,{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const h=document.querySelector(".gallery");function g(o){const t=o.map(n=>`
      <li class="gallery-item">
        <img src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
        <div class="meta">
          <div><b>Likes</b> ${n.likes}</div>
          <div><b>Views</b> ${n.views}</div>
          <div><b>Comments</b> ${n.comments}</div>
          <div><b>Downloads</b> ${n.downloads}</div>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t)}function w(){h.innerHTML=""}function S(){document.querySelector(".load-more").classList.remove("hidden")}function p(){document.querySelector(".load-more").classList.add("hidden")}const m=document.querySelector(".form"),f=document.querySelector(".load-more"),s=document.querySelector(".loader-text");document.querySelector(".gallery");let i="",a=1,d=0;m.addEventListener("submit",async o=>{if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),a=1,w(),p(),m.insertAdjacentElement("afterend",s),s.classList.remove("hidden"),!!i)try{const t=await y(i,a);if(t.hits.length===0){c.error({message:"No images found."});return}g(t.hits),d=Math.ceil(t.totalHits/15),a<d&&S()}catch{c.error({message:"Something went wrong"})}finally{s.classList.add("hidden")}});f.addEventListener("click",async()=>{a+=1,f.insertAdjacentElement("beforebegin",s),s.classList.remove("hidden");try{const o=await y(i,a);g(o.hits),a>=d&&(p(),c.info({message:"You've reached the end of search results."}));const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{c.error({message:"Something went wrong"})}finally{s.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
