import{a as p,i}from"./assets/vendor-BUg1UuD4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&u(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const v="49725006-00816a3e1de0585a9b0ca4d46",L="https://pixabay.com/api/";async function f(r,t){return(await p.get(L,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const y=document.querySelector(".gallery");function h(r){const t=r.map(s=>`
      <li class="gallery-item">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
        <div class="meta">
          <div><b>Likes</b> ${s.likes}</div>
          <div><b>Views</b> ${s.views}</div>
          <div><b>Comments</b> ${s.comments}</div>
          <div><b>Downloads</b> ${s.downloads}</div>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",t)}function b(){y.innerHTML=""}function w(){document.querySelector(".load-more").classList.remove("hidden")}function g(){document.querySelector(".load-more").classList.add("hidden")}const S=document.querySelector("#search-form"),q=document.querySelector(".load-more"),m=document.querySelector(".loader-text"),c=document.querySelector(".loader-text.bottom");document.querySelector(".gallery");let n="",a=1,l=0;S.addEventListener("submit",async r=>{if(r.preventDefault(),n=r.target.elements.searchQuery.value.trim(),a=1,b(),g(),m.classList.remove("hidden"),c.classList.add("hidden"),!!n)try{const t=await f(n,a);if(t.hits.length===0){i.error({message:"No images found."});return}h(t.hits),l=Math.ceil(t.totalHits/15),a<l&&w()}catch{i.error({message:"Something went wrong"})}finally{m.classList.add("hidden"),c.classList.remove("hidden")}});q.addEventListener("click",async()=>{a+=1,c.classList.remove("hidden");try{const r=await f(n,a);h(r.hits),a>=l&&(g(),i.info({message:"You've reached the end of search results."}));const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{i.error({message:"Something went wrong"})}finally{c.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
