import{a as g,S as L,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const b="49725006-00816a3e1de0585a9b0ca4d46",w="https://pixabay.com/api/";async function m(r,t){return(await g.get(w,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const p=document.querySelector(".gallery");document.querySelector(".loader");const h=document.querySelector(".load-more");let S=new L(".gallery a",{captionsData:"alt",captionDelay:250});function f(r){const t=r.map(a=>`
      <li class="gallery-item">
        <a href="${a.largeImageURL}">
          <img src="${a.webformatURL}" alt="${a.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${a.likes}</p>
          <p><b>Views</b> ${a.views}</p>
          <p><b>Comments</b> ${a.comments}</p>
          <p><b>Downloads</b> ${a.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",t),S.refresh()}function v(){p.innerHTML=""}function q(){h.classList.remove("hidden")}function y(){h.classList.add("hidden")}const P=document.querySelector(".form"),R=document.querySelector(".load-more"),i=document.querySelector(".loader");document.querySelector(".gallery");let l="",s=1,d=0;P.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements.searchQuery.value.trim(),s=1,v(),y(),i.classList.remove("hidden"),!l){n.warning({message:"Please enter a search term!",position:"topRight"}),i.classList.add("hidden");return}try{const t=await m(l,s);if(t.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f(t.hits),d=Math.ceil(t.totalHits/15),s<d&&q()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{i.classList.add("hidden")}});R.addEventListener("click",async()=>{s+=1,i.classList.remove("hidden");try{const r=await m(l,s);f(r.hits),s>=d&&(y(),n.info({message:"You've reached the end of search results.",position:"topRight"}));const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{i.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
